-- EKIN / Supabase RAG setup
-- Reconstructed from the live "Enterprise RAG Chatbot" Supabase project on 2026-08-02.
-- This schema intentionally exposes no API keys or credentials.

create extension if not exists vector;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(3072),
  created_at timestamptz not null default timezone('utc'::text, now())
);

-- The live project uses RLS with no public policies because n8n accesses
-- the table through a server-side Supabase service-role credential.
alter table public.documents enable row level security;

-- Metadata filtering used by match_documents.
create index if not exists documents_metadata_gin_idx
  on public.documents using gin (metadata);

-- HNSW cosine index. halfvec reduces index memory while retaining 3072 dimensions.
create index if not exists documents_embedding_hnsw_idx
  on public.documents
  using hnsw ((embedding::halfvec(3072)) halfvec_cosine_ops);

create or replace function public.match_documents(
  query_embedding vector,
  match_count integer default 5,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
set search_path to 'public', 'extensions'
as $function$
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.documents d
  where d.embedding is not null
    and d.metadata @> filter
  order by (d.embedding::halfvec(3072)) <=> (query_embedding::halfvec(3072))
  limit least(greatest(match_count, 1), 50);
$function$;
